apiVersion: 1

datasources:
  - name: QuickMart SQLite
    uid: quickmart-sqlite
    type: frser-sqlite-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      path: /data/quickmart.sqlite3